<?php
/**
 * @author Harry Tang <harry@powerkernel.com>
 * @link https://powerkernel.com
 * @copyright Copyright (c) 2018 Power Kernel
 */

namespace powerkernel\yiilaundry\models;

use powerkernel\yiicommon\behaviors\UTCDateTimeBehavior;
use powerkernel\yiiuser\models\User;
use powerkernel\yiilaundry\models\Order;
use Yii;
class OrderHistory extends \yii\mongodb\ActiveRecord
{

    
    public function attributes()
    {
        return [
            '_id',
            'order_id',
            'status',
            'created_by',
            'updated_by',
            'created_at',
            'updated_at'
        ];
    }
    public function rules()
    {
        return [
            [['order_id','status'], 'required'],       
            ['status', 'in', 'range' => ['Picked Up','Pick Up','Dropped','Completed','Delivered','Picked Up Back','Cancelled']],
            [['order_id'], 'exist', 'targetClass' => Order::class, 'targetAttribute' => ['order_id' => '_id']],
            [['created_by'], 'exist', 'targetClass' => User::class, 'targetAttribute' => ['created_by' => '_id']],
            [['updated_by'], 'exist', 'targetClass' => User::class, 'targetAttribute' => ['updated_by' => '_id']],
        ];
    }
    public function behaviors()
    {
        return [
            UTCDateTimeBehavior::class,
        ];
    }
    public function beforeSave($insert)
    {
        if ($insert) {
            $this->created_by = (string)Yii::$app->user->id;
        }
        $this->updated_by = (string)Yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
